name: maps_toolkit
description: Maps toolkit - geo-measurements utils - area of polygon, distance
  between point, heading and offset between points (port of SphericalUtil,
  PolyUtil from `android-maps-utils`).
version: 2.0.0
homepage: https://github.com/kb0/maps_toolkit/

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  google_maps_flutter: ^2.1.1

dev_dependencies:
  pedantic: ">=1.8.0 <3.0.0"
  test: any
